
name: tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ master-origin ]


jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-18.04
    runs-on: ${{ matrix.os }}
    steps:
      - run: bash install/ubuntu.sh
        name: Check sets up the environment
