
name: tests
on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ master-origin ]


jobs:
  build-ubuntu:
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: bash install/ubuntu.sh
        name: Check sets up the environment

  build-osx:
    strategy:
      matrix:
        os:
          - macos-11
          - macos-10.05
    steps:
      - uses: actions/checkout@v2
      - run: bash install/osx.sh
        name: Check sets up the environment
