
name: tests
on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ master-origin ]


jobs:
  build-ubuntu:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-20.04
          - ubuntu-18.04
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: bash install/ubuntu.sh
        name: Check sets up the environment

  build-osx:
    strategy:
      matrix:
        os:
          - macos-latest
          - macos-11
          # Don't run this systems as there are practically no workers
          # - macos-10.05
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: bash install/osx.sh
        name: Check sets up the environment
